services: 
 ntopng:
    hostname: ntopng
    image: ntop/ntopng:latest
    container_name: ntopng
    healthcheck:
       test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3222' || exit 1
       interval: 10s
       timeout: 5s
       retries: 3
       start_period: 90s
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    volumes:
      - /mnt/docker/ntopng:/var/lib/ntopng:rw
    network_mode: host
    stdin_open: true
    tty: true
    command: ["-i", "eth0", "-w", "3222"]    